---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Magic Machine Deployment Template
Parameters:
  Bucket:
    Type: String
    Default: owen-public-production-bucket

  InstanceType:
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.medium

  Key:
    Type: AWS::EC2::KeyPair::KeyName
    Default: Owen

  CIDR:
    Type: String
    Default: 10.0.0.0/16

  SubnetCIDR:
    Type: String
    Default: 10.0.0.0/20

Resources:
  InstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:                # optional, map of String
        InstanceType: !Ref InstanceType
        Key: !Ref Key
        Subnet: !GetAtt VPCStack.Outputs.PublicSubnet
        VPC: !GetAtt VPCStack.Outputs.VPC
      TemplateURL: !Sub 'https://s3.amazonaws.com/${Bucket}/MagicOnlineMachine/Instance/template.yaml'
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:                # optional, map of String
        SubnetCIDR: !Ref SubnetCIDR
        CIDR: !Ref CIDR
      TemplateURL: !Sub 'https://s3.amazonaws.com/${Bucket}/MagicOnlineMachine/VPC/template.yaml'
