---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  EC2 Instance running windows AMI for Magic Online

Parameters:

  InstanceType:
    Type: String
    AllowedValues:
      - t2.medium
  Key:
    Type: AWS::EC2::KeyPair::KeyName

  Subnet:
    Type: AWS::EC2::Subnet::Id

  VPC:
    Type: AWS::EC2::VPC::Id

  Subnet:
    Type: AWS::EC2::SecurityGroup::Id

#Mappings:

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
      ImageId: ami-0703fc157f1b87f6c
      InstanceType: !Ref InstanceType
      KeyName: !Ref Key
      SecurityGroupIds: !Ref SG
      SubnetId: !Ref Subnet
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows RDP to all internet.
      GroupName: MagicMachineSG
      SecurityGroupIngress:                # optional, list of Ingress
        - CidrIp: 0.0.0.0/0
          FromPort: 3389
          IpProtocol: tcp
          ToPort: 3389
      VpcId: !Ref VPC

Outputs:
  InstanceId:
    Value: !Ref Instance
  InstancePublicDnsName:
    Value: !GetAtt Instance.PublicDnsName
